import { IsInt, IsOptional, IsString, Min, IsBoolean, IsNotEmpty, ValidateIf } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class StageUpdateDto {
  @ApiProperty({ description: 'Quantity received at current stage', example: 500 })
  @IsInt()
  @Min(0)
  qtyReceived: number;

  @ApiProperty({ description: 'Quantity processed at current stage', example: 500 })
  @IsInt()
  @Min(0)
  qtyProcessed: number;

  @ApiProperty({ description: 'Quantity forwarded to next stage (or completed)', example: 480 })
  @IsInt()
  @Min(0)
  qtyForwarded: number;

  @ApiPropertyOptional({ description: 'Quantity rejected as scrap', example: 10, default: 0 })
  @IsOptional()
  @IsInt()
  @Min(0)
  qtyRejected?: number = 0;

  @ApiPropertyOptional({ description: 'Quantity placed on hold', example: 10, default: 0 })
  @IsOptional()
  @IsInt()
  @Min(0)
  qtyHold?: number = 0;

  @ApiPropertyOptional({ description: 'Mandatory reason if qtyRejected > 0' })
  @ValidateIf((o) => (o.qtyRejected ?? 0) > 0)
  @IsNotEmpty({ message: 'rejectionReason is mandatory when rejected quantity is greater than 0' })
  @IsString()
  rejectionReason?: string;

  @ApiPropertyOptional({ description: 'General operator remarks' })
  @IsOptional()
  @IsString()
  remarks?: string;

  @ApiPropertyOptional({ description: 'Whether this is an admin/planner override', default: false })
  @IsOptional()
  @IsBoolean()
  isOverride?: boolean = false;

  @ApiPropertyOptional({ description: 'Idempotency key generated by client (UUID)' })
  @IsOptional()
  @IsString()
  clientRequestId?: string;
}
